title: "Muhammad | Cybersecurity"
tagline: "Biograophy"
description: "Cybersecurity student exploring cloud security, networks, and secure systems."
lang: en
timezone: Asia/Karachi

url: "https://mightykarim.github.io"
baseurl: "/Muhammadkhalidkarim" # Set to '' if using a user/organization pages repo

# theme: jekyll-theme-chirpy  # DISABLED - using custom layouts instead
permalink: /writeups/:title/

# Ensure HTML files are processed
include:
  - "_pages"

github:
  username: mightyKarim

social:
  name: "Muhammad"
  links:
    - https://github.com/mightyKarim
    - https://www.linkedin.com/in/muhammad-karim-9464b7247

email: "muhammadd.khalidkarim@gmail.com"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile.lock
  - node_modules
  - vendor
  - README.old.md
