title: "Muhammad | Cybersecurity"
tagline: "Biograophy"
description: "Cybersecurity student exploring cloud security, networks, and secure systems."
lang: en
timezone: Asia/Karachi

url: "https://mightykareem.github.io"
baseurl: "/Muhammadkhalidkarim" # Set to '' if using a user/organization pages repo

# theme: jekyll-theme-chirpy  # DISABLED - using custom layouts instead
paginate: 10
paginate_path: /page:num/
permalink: /writeups/:title/

github:
  username: MightyKareem

social:
  name: "Muhammad"
  links:
    - https://github.com/MightyKareem
    - https://www.linkedin.com/in/muhammad-karim-9464b7247

email: "muhammadd.khalidkarim@gmail.com"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile.lock
  - node_modules
  - vendor
  - README.old.md
